[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = [
    "cd backend",
    "pip install -r requirements_production.txt"
]

[phases.build]
cmds = [
    "cd backend",
    "python manage.py migrate --settings=transport_booking.settings_production",
    "python manage.py collectstatic --settings=transport_booking.settings_production --noinput"
]

[start]
cmd = "cd backend && gunicorn transport_booking.wsgi:application --bind 0.0.0.0:$PORT --workers 3 --timeout 120 --worker-class gthread --env DJANGO_SETTINGS_MODULE=transport_booking.settings_production"
