"""
Django settings for transport_booking project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-your-secret-key-here'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'unfold',  # Must be first
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'import_export',
    'booking',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'transport_booking.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'transport_booking.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:5174",
    "http://127.0.0.1:5174"
]

CORS_ALLOW_CREDENTIALS = True

# Email settings (for development, using console backend)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'asivasabariganesan@gmail.com')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', 'oukx hdff aojz iryq')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'asivasabariganesan@gmail.com')

# Custom user model
AUTH_USER_MODEL = 'booking.Student'

# Django Unfold Configuration
UNFOLD = {
    "SITE_TITLE": "College Transport Admin",
    "SITE_HEADER": "College Transport",
    "SITE_SYMBOL": "🚌",
    "COLORS": {
        "primary": {
            "50": "250 245 255",
            "100": "243 232 255", 
            "200": "233 213 255",
            "300": "216 180 254",
            "400": "196 181 253",
            "500": "168 85 247",
            "600": "147 51 234",
            "700": "126 34 206",
            "800": "107 33 168",
            "900": "88 28 135",
            "950": "59 7 100",
        },
    },
    "STYLES": [
        """
        :root {
            --primary-50: 250 245 255;
            --primary-100: 243 232 255;
            --primary-200: 233 213 255;
            --primary-300: 216 180 254;
            --primary-400: 196 181 253;
            --primary-500: 168 85 247;
            --primary-600: 147 51 234;
            --primary-700: 126 34 206;
            --primary-800: 107 33 168;
            --primary-900: 88 28 135;
            --primary-950: 59 7 100;
        }
        
        /* Light Mode Styles */
        [data-theme="light"] {
            --bg-primary: #ffffff;
            --bg-secondary: #f9fafb;
            --bg-tertiary: #f3f4f6;
            --text-primary: #374151;
            --text-secondary: #6b7280;
            --border-color: #e5e7eb;
            --input-bg: #ffffff;
            --input-border: #d1d5db;
            --card-bg: #ffffff;
            --header-bg: #ffffff;
            --sidebar-bg: #f9fafb;
        }
        
        /* Dark Mode Styles */
        [data-theme="dark"] {
            --bg-primary: #1f2937;
            --bg-secondary: #111827;
            --bg-tertiary: #374151;
            --text-primary: #f9fafb;
            --text-secondary: #d1d5db;
            --border-color: #374151;
            --input-bg: #374151;
            --input-border: #4b5563;
            --card-bg: #1f2937;
            --header-bg: #111827;
            --sidebar-bg: #111827;
        }
        
        /* Theme Toggle Button */
        .theme-toggle {
            position: fixed;
            top: 1rem;
            right: 1rem;
            z-index: 1000;
            background: linear-gradient(135deg, #a855f7, #8b5cf6);
            border: none;
            border-radius: 50%;
            width: 48px;
            height: 48px;
            cursor: pointer;
            display: flex;
            align-items: center;
            justify-content: center;
            color: white;
            font-size: 1.2rem;
            box-shadow: 0 4px 12px rgba(168, 85, 247, 0.3);
            transition: all 0.3s ease;
        }
        
        .theme-toggle:hover {
            transform: scale(1.1);
            box-shadow: 0 6px 16px rgba(168, 85, 247, 0.4);
        }
        
        /* Global Theme Application */
        * {
            transition: background-color 0.3s ease, color 0.3s ease, border-color 0.3s ease;
        }
        
        body {
            background-color: var(--bg-primary) !important;
            color: var(--text-primary) !important;
        }
        
        /* Header and Navigation */
        header, .unfold-header, .unfold-admin header {
            background-color: var(--header-bg) !important;
            color: var(--text-primary) !important;
            border-bottom: 1px solid var(--border-color) !important;
        }
        
        /* Sidebar */
        .unfold-sidebar, .unfold-admin .unfold-sidebar, aside {
            background-color: var(--sidebar-bg) !important;
            color: var(--text-primary) !important;
            border-right: 1px solid var(--border-color) !important;
        }
        
        /* Main Content Area */
        .unfold-content, .unfold-admin .unfold-content, main {
            background-color: var(--bg-primary) !important;
            color: var(--text-primary) !important;
        }
        
        /* Cards and Containers */
        .card, .unfold-card, .unfold-admin .card {
            background-color: var(--card-bg) !important;
            color: var(--text-primary) !important;
            border: 1px solid var(--border-color) !important;
        }
        
        /* Form Elements */
        input, select, textarea, .unfold-admin input, .unfold-admin select, .unfold-admin textarea {
            background-color: var(--input-bg) !important;
            border: 1px solid var(--input-border) !important;
            color: var(--text-primary) !important;
        }
        
        input:focus, select:focus, textarea:focus,
        .unfold-admin input:focus, .unfold-admin select:focus, .unfold-admin textarea:focus {
            border-color: #a855f7 !important;
            box-shadow: 0 0 0 3px rgba(168, 85, 247, 0.1) !important;
        }
        
        /* Tables */
        table, .unfold-admin table {
            background-color: var(--bg-primary) !important;
            color: var(--text-primary) !important;
        }
        
        th, .unfold-admin th {
            background-color: var(--bg-secondary) !important;
            color: var(--text-primary) !important;
            border-color: var(--border-color) !important;
        }
        
        td, .unfold-admin td {
            border-color: var(--border-color) !important;
            background-color: var(--bg-primary) !important;
        }
        
        tr:hover, .unfold-admin tr:hover {
            background-color: var(--bg-tertiary) !important;
        }
        
        /* Buttons */
        .button, input[type="submit"], .unfold-admin .button, .unfold-admin input[type="submit"] {
            background: linear-gradient(135deg, #a855f7, #8b5cf6) !important;
            color: white !important;
            border: none !important;
            border-radius: 6px !important;
            padding: 8px 16px !important;
            transition: all 0.3s ease !important;
        }
        
        .button:hover, input[type="submit"]:hover,
        .unfold-admin .button:hover, .unfold-admin input[type="submit"]:hover {
            transform: translateY(-1px) !important;
            box-shadow: 0 4px 12px rgba(168, 85, 247, 0.3) !important;
        }
        
        /* Links */
        a, .unfold-admin a {
            color: #a855f7 !important;
        }
        
        a:hover, .unfold-admin a:hover {
            color: #8b5cf6 !important;
        }
        
        /* Dropdowns and Selects */
        select option {
            background-color: var(--input-bg) !important;
            color: var(--text-primary) !important;
        }
        
        /* Search and Filter Areas */
        .search, .filter, .unfold-admin .search, .unfold-admin .filter {
            background-color: var(--bg-secondary) !important;
            color: var(--text-primary) !important;
            border: 1px solid var(--border-color) !important;
        }
        
        /* Breadcrumbs */
        .breadcrumbs, .unfold-admin .breadcrumbs {
            background-color: var(--bg-secondary) !important;
            color: var(--text-secondary) !important;
        }
        
        /* Pagination */
        .pagination, .unfold-admin .pagination {
            background-color: var(--bg-primary) !important;
            color: var(--text-primary) !important;
        }
        
        .pagination a, .unfold-admin .pagination a {
            background-color: var(--bg-secondary) !important;
            color: var(--text-primary) !important;
            border: 1px solid var(--border-color) !important;
        }
        
        /* Messages and Alerts */
        .message, .alert, .unfold-admin .message, .unfold-admin .alert {
            background-color: var(--bg-secondary) !important;
            color: var(--text-primary) !important;
            border: 1px solid var(--border-color) !important;
        }
        
        /* Tooltips and Popups */
        .tooltip, .popup, .unfold-admin .tooltip, .unfold-admin .popup {
            background-color: var(--card-bg) !important;
            color: var(--text-primary) !important;
            border: 1px solid var(--border-color) !important;
        }
        
        /* Checkboxes and Radio Buttons */
        input[type="checkbox"], input[type="radio"] {
            background-color: var(--input-bg) !important;
            border-color: var(--input-border) !important;
        }
        
        /* File Inputs */
        input[type="file"] {
            background-color: var(--bg-secondary) !important;
            color: var(--text-primary) !important;
        }
        
        /* Disabled Elements */
        input:disabled, select:disabled, textarea:disabled,
        .unfold-admin input:disabled, .unfold-admin select:disabled, .unfold-admin textarea:disabled {
            background-color: var(--bg-tertiary) !important;
            color: var(--text-secondary) !important;
        }
        """,
    ],
}