# Generated by Django 4.2.23 on 2025-08-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_from_location_booking_to_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='from_location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bus',
            name='to_location',
            field=models.CharField(default='', max_length=100),
        ),
    ]
