# Generated by Django 4.2.23 on 2025-08-23 13:16

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_bus_from_location_bus_to_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='trip_types',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('RETURN', 'Return Trip'), ('WEEKEND', 'Weekend Trip')], default=['RETURN'], max_length=14),
        ),
    ]
