# Generated by Django 4.2.23 on 2025-08-23 13:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_bus_trip_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='trip_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
