# Generated by Django 4.2.23 on 2025-08-23 13:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_trip_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='departure_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
