# Generated by Django 4.2.23 on 2025-08-23 13:49

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_booking_departure_time_booking_return_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='departure_time',
            field=models.TimeField(default=booking.models.get_default_time),
        ),
        migrations.AlterField(
            model_name='booking',
            name='return_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
