# Generated by Django 4.2.23 on 2025-08-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_booking_departure_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='return_dates',
            field=models.JSONField(blank=True, default=list, help_text='List of return trip dates when this bus is available (YYYY-MM-DD format)'),
        ),
        migrations.AddField(
            model_name='bus',
            name='weekend_dates',
            field=models.JSONField(blank=True, default=list, help_text='List of weekend dates when this bus is available (YYYY-MM-DD format)'),
        ),
    ]
