# Generated by Django 4.2.23 on 2025-08-23 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_add_departure_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='return_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='trip_type',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='return_dates',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='return_time',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='trip_types',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='weekend_dates',
        ),
    ]
