# Generated by Django 4.2.7 on 2025-08-28 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('is_pickup', models.BooleanField(default=True, help_text='Is this a pickup point?')),
                ('is_dropoff', models.BooleanField(default=True, help_text='Is this a drop-off point?')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='booking.bus')),
            ],
            options={
                'ordering': ['stop_name', 'location'],
                'unique_together': {('bus', 'stop_name', 'location')},
            },
        ),
        migrations.DeleteModel(
            name='Route',
        ),
    ]
