# Generated by Django 4.2.7 on 2025-08-29 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_stop_delete_route'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.AlterModelOptions(
            name='bookingotp',
            options={'verbose_name': 'Booking OTP', 'verbose_name_plural': 'Booking OTPs'},
        ),
        migrations.AlterModelOptions(
            name='bus',
            options={'verbose_name': 'Bus', 'verbose_name_plural': 'Buses'},
        ),
        migrations.AlterModelOptions(
            name='stop',
            options={'ordering': ['stop_name', 'location'], 'verbose_name': 'Stop', 'verbose_name_plural': 'Stops'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AddField(
            model_name='booking',
            name='dropoff_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dropoff_bookings', to='booking.stop'),
        ),
        migrations.AddField(
            model_name='booking',
            name='dropoff_stop_name',
            field=models.CharField(blank=True, help_text='Human readable dropoff stop name', max_length=200),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pickup_bookings', to='booking.stop'),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_stop_name',
            field=models.CharField(blank=True, help_text='Human readable pickup stop name', max_length=200),
        ),
    ]
