# Generated by Django 4.2.7 on 2025-08-29 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_alter_booking_options_alter_bookingotp_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='dropoff_stop',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='dropoff_stop_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pickup_stop',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pickup_stop_name',
        ),
        migrations.AddField(
            model_name='booking',
            name='selected_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_selected', to='booking.stop'),
        ),
    ]
