# Generated by Django 4.2.7 on 2025-08-29 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_siteconfiguration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='degree_type',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_type',
        ),
    ]
