# Generated by Django 4.2.7 on 2025-08-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_remove_student_degree_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='booking_open',
            field=models.BooleanField(default=True, help_text='If disabled, students cannot create new bookings'),
        ),
    ]
