# Generated by Django 4.2.7 on 2025-08-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_siteconfiguration_booking_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='is_booking_open',
            field=models.BooleanField(default=True, help_text='If disabled, this bus cannot be booked'),
        ),
    ]
