# Generated by Django 4.2.7 on 2025-08-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_bus_is_booking_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_outbound_trip',
            field=models.BooleanField(default=True, help_text='True = FROM REC, False = TO REC'),
        ),
        migrations.AddField(
            model_name='booking',
            name='outbound_booking_date',
            field=models.DateTimeField(blank=True, help_text='When outbound trip was booked', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_trip_available_after',
            field=models.DateTimeField(blank=True, help_text='24hrs after outbound booking', null=True),
        ),
    ]
