# Generated by Django 4.2.7 on 2025-08-29 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_alter_booking_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
    ]
